# Generated by Django 5.0.14 on 2026-05-17 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('palabra_clave', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria de interes',
                'verbose_name_plural': 'categorias de interes',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FuenteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('marketplace', 'Marketplace'), ('tienda', 'Tienda'), ('manual', 'Manual')], max_length=20)),
                ('url_base', models.URLField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fuente de producto',
                'verbose_name_plural': 'fuentes de producto',
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_reventa_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_margen', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tipo', models.CharField(choices=[('afiliado', 'Afiliado'), ('reventa', 'Reventa'), ('descartar', 'Descartar')], max_length=20)),
                ('puntaje', models.PositiveIntegerField(default=0)),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('publicado', 'Publicado'), ('comprado', 'Comprado'), ('descartado', 'Descartado')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-puntaje', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gancho', models.CharField(max_length=255)),
                ('guion_corto', models.TextField()),
                ('descripcion', models.TextField()),
                ('hashtags', models.CharField(max_length=255)),
                ('generado_con_ia', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='oportunidades.oportunidad')),
            ],
            options={
                'verbose_name': 'contenido sugerido',
                'verbose_name_plural': 'contenidos sugeridos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=150, null=True)),
                ('reputacion_vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('reacondicionado', 'Reacondicionado'), ('desconocido', 'Desconocido')], max_length=50)),
                ('es_chico_liviano', models.BooleanField(default=False)),
                ('es_fragil', models.BooleanField(default=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oportunidades.categoriainteres')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oportunidades.fuenteproducto')),
            ],
            options={
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('fecha_relevamiento', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='oportunidades.producto')),
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de producto',
                'ordering': ['-fecha_relevamiento'],
            },
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='oportunidades.producto'),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_social', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('otra', 'Otra')], max_length=20)),
                ('fecha_publicacion', models.DateTimeField()),
                ('url_publicacion', models.URLField(blank=True, null=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('clics', models.PositiveIntegerField(default=0)),
                ('ventas_reportadas', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='oportunidades.oportunidad')),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
