# Generated by Django 5.0 on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oportunidades", "0004_decisiontecnica_fuenteweb_categoriafuente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacionProductos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to="importaciones/productos/")),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel XLSX"),
                            ("xls", "Excel XLS"),
                            ("desconocido", "Desconocido"),
                        ],
                        default="desconocido",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("procesada", "Procesada"),
                            ("procesada_con_errores", "Procesada con errores"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                ("total_filas", models.PositiveIntegerField(default=0)),
                ("filas_procesadas", models.PositiveIntegerField(default=0)),
                ("productos_creados", models.PositiveIntegerField(default=0)),
                ("productos_actualizados", models.PositiveIntegerField(default=0)),
                ("precios_creados", models.PositiveIntegerField(default=0)),
                ("errores", models.PositiveIntegerField(default=0)),
                ("mensaje_error", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_procesamiento", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "fuente_web",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importaciones",
                        to="oportunidades.fuenteweb",
                    ),
                ),
            ],
            options={
                "verbose_name": "importacion de productos",
                "verbose_name_plural": "importaciones de productos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetalleImportacionProducto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_fila", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("procesada", "Procesada"), ("omitida", "Omitida"), ("error", "Error")],
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField(blank=True, null=True)),
                ("datos_originales", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "importacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="oportunidades.importacionproductos",
                    ),
                ),
                (
                    "precio_fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="oportunidades.preciofuente",
                    ),
                ),
                (
                    "producto_fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="oportunidades.productofuente",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de importacion de producto",
                "verbose_name_plural": "detalles de importacion de productos",
                "ordering": ["importacion", "numero_fila"],
            },
        ),
    ]
