# Generated by Django 5.0.14 on 2026-05-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0005_importacionproductos_detalleimportacionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectorFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_conector', models.CharField(choices=[('csv_manual', 'CSV manual'), ('excel_manual', 'Excel manual'), ('csv_remoto', 'CSV remoto'), ('excel_remoto', 'Excel remoto'), ('api_oficial', 'API oficial'), ('catalogo_pdf', 'Catalogo PDF'), ('carga_url', 'Carga URL'), ('scraping_permitido', 'Scraping permitido'), ('otro', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('error', 'Error'), ('deshabilitado', 'Deshabilitado')], default='borrador', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('frecuencia_sugerida', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_revision_manual', models.BooleanField(default=True)),
                ('respeta_politica_fuente', models.BooleanField(default=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conectores', to='oportunidades.fuenteweb')),
            ],
            options={
                'verbose_name': 'conector de fuente',
                'verbose_name_plural': 'conectores de fuente',
                'ordering': ['fuente_web', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='importacionproductos',
            name='conector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to='oportunidades.conectorfuente'),
        ),
        migrations.CreateModel(
            name='EjecucionConector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('finalizada', 'Finalizada'), ('finalizada_con_errores', 'Finalizada con errores'), ('error', 'Error'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('productos_detectados', models.PositiveIntegerField(default=0)),
                ('productos_creados', models.PositiveIntegerField(default=0)),
                ('productos_actualizados', models.PositiveIntegerField(default=0)),
                ('precios_creados', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('log_resumido', models.TextField(blank=True, null=True)),
                ('conector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='oportunidades.conectorfuente')),
            ],
            options={
                'verbose_name': 'ejecucion de conector',
                'verbose_name_plural': 'ejecuciones de conectores',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEjecucionConector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('procesado', 'Procesado'), ('omitido', 'Omitido'), ('error', 'Error')], max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('datos_originales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='oportunidades.ejecucionconector')),
            ],
            options={
                'verbose_name': 'detalle de ejecucion de conector',
                'verbose_name_plural': 'detalles de ejecuciones de conectores',
                'ordering': ['ejecucion', 'fecha_creacion'],
            },
        ),
    ]
