# Generated by Django 5.0.14 on 2026-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0006_conectorfuente_importacionproductos_conector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conectorfuente',
            name='formato_recurso',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel XLSX'), ('xls', 'Excel XLS'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='conectorfuente',
            name='fuente_autorizo_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conectorfuente',
            name='notas_uso_datos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conectorfuente',
            name='requiere_descarga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conectorfuente',
            name='url_recurso',
            field=models.URLField(blank=True, null=True),
        ),
    ]
