# Generated by Django 5.0.14 on 2026-05-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0007_conectorfuente_formato_recurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaFuenteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_robots_txt', models.URLField(blank=True, null=True)),
                ('robots_txt_encontrado', models.BooleanField(default=False)),
                ('robots_txt_contenido_resumen', models.TextField(blank=True, null=True)),
                ('sitemap_detectado', models.BooleanField(default=False)),
                ('sitemap_url', models.URLField(blank=True, null=True)),
                ('requiere_login_detectado', models.BooleanField(default=False)),
                ('captcha_detectado', models.BooleanField(default=False)),
                ('bloqueos_detectados', models.BooleanField(default=False)),
                ('status_home', models.PositiveIntegerField(blank=True, null=True)),
                ('status_robots', models.PositiveIntegerField(blank=True, null=True)),
                ('status_sitemap', models.PositiveIntegerField(blank=True, null=True)),
                ('permite_extraccion_segun_revision', models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('dudoso', 'Dudoso'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('metodo_recomendado', models.CharField(choices=[('api_oficial', 'API oficial'), ('csv_excel', 'CSV/Excel'), ('catalogo_pdf', 'Catalogo PDF'), ('sitemap', 'Sitemap'), ('datos_estructurados', 'Datos estructurados'), ('carga_url', 'Carga URL'), ('scraping_controlado', 'Scraping controlado'), ('no_automatizar', 'No automatizar'), ('pendiente_revision', 'Pendiente revision')], default='pendiente_revision', max_length=40)),
                ('semaforo_sugerido', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('resumen_tecnico', models.TextField(blank=True, null=True)),
                ('riesgos_detectados', models.TextField(blank=True, null=True)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('revisado_manualmente', models.BooleanField(default=False)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
                ('fuente_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='oportunidades.fuenteweb')),
            ],
            options={
                'verbose_name': 'auditoria de fuente web',
                'verbose_name_plural': 'auditorias de fuentes web',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='RecursoFuenteDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('robots_txt', 'Robots.txt'), ('sitemap', 'Sitemap'), ('categoria', 'Categoria'), ('producto', 'Producto'), ('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('feed', 'Feed'), ('pagina_info', 'Pagina info'), ('otro', 'Otro')], max_length=30)),
                ('url', models.URLField()),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=150, null=True)),
                ('permitido', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_detectado', models.DateTimeField(auto_now_add=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='oportunidades.auditoriafuenteweb')),
            ],
            options={
                'verbose_name': 'recurso de fuente detectado',
                'verbose_name_plural': 'recursos de fuentes detectados',
                'ordering': ['-fecha_detectado'],
            },
        ),
    ]
