# Generated by Django 5.0.14 on 2026-05-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0008_auditoriafuenteweb_recursofuentedetectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionExtractorWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_inicio', models.URLField()),
                ('url_categoria', models.URLField(blank=True, null=True)),
                ('dominio_permitido', models.CharField(max_length=200)),
                ('modo_extraccion', models.CharField(choices=[('json_ld', 'JSON-LD'), ('css_selectors', 'Selectores CSS'), ('mixto', 'Mixto'), ('preview_manual', 'Preview manual')], default='preview_manual', max_length=30)),
                ('product_card_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('title_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('price_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('url_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('image_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('description_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('next_page_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('max_paginas', models.PositiveIntegerField(default=1)),
                ('max_productos', models.PositiveIntegerField(default=20)),
                ('delay_segundos', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('timeout_segundos', models.PositiveIntegerField(default=15)),
                ('habilitado', models.BooleanField(default=False)),
                ('solo_preview', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_web', to='oportunidades.conectorfuente')),
            ],
            options={
                'verbose_name': 'configuracion de extractor web',
                'verbose_name_plural': 'configuraciones de extractores web',
            },
        ),
        migrations.CreateModel(
            name='ResultadoExtraccionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_decimal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('url_producto', models.URLField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fuente_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('detectado', 'Detectado'), ('procesado', 'Procesado'), ('omitido', 'Omitido'), ('error', 'Error')], default='detectado', max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_web', to='oportunidades.ejecucionconector')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
            ],
            options={
                'verbose_name': 'resultado de extraccion web',
                'verbose_name_plural': 'resultados de extraccion web',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
