# Generated by Django 5.0.14 on 2026-05-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0009_configuracionextractorweb_resultadoextraccionweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionextractorweb',
            name='pagina_prueba_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionextractorweb',
            name='requiere_js_detectado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionextractorweb',
            name='ultima_revision_selectores',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionextractorweb',
            name='ultimo_preview_mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionextractorweb',
            name='ultimo_preview_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RevisionManualFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_revision', models.CharField(choices=[('terminos', 'Terminos'), ('robots', 'Robots'), ('privacidad', 'Privacidad'), ('comercial', 'Comercial'), ('otra', 'Otra')], max_length=30)),
                ('url_revisada', models.URLField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('permite', 'Permite'), ('prohibe', 'Prohibe'), ('dudoso', 'Dudoso'), ('no_encontrado', 'No encontrado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=30)),
                ('resumen', models.TextField()),
                ('decision', models.TextField(blank=True, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('aplicar_a_politica', models.BooleanField(default=False)),
                ('fuente_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_manuales', to='oportunidades.fuenteweb')),
            ],
            options={
                'verbose_name': 'revision manual de fuente',
                'verbose_name_plural': 'revisiones manuales de fuentes',
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
