# Generated by Django 5.0.14 on 2026-05-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0010_configuracionextractorweb_pagina_prueba_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='motivo_no_procesable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='procesable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
