# Generated by Django 5.0.14 on 2026-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0011_resultadoextraccionweb_fecha_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='duplicado_probable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='motivo_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='score_preview',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
