# Generated by Django 5.0.14 on 2026-05-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0012_resultadoextraccionweb_duplicado_probable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionLaboratorioMapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('estado', models.CharField(choices=[('analizada', 'Analizada'), ('guardada', 'Guardada'), ('procesada', 'Procesada'), ('error', 'Error')], default='analizada', max_length=20)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('requiere_js_probable', models.BooleanField(default=False)),
                ('tiene_json_ld', models.BooleanField(default=False)),
                ('bloqueos_detectados', models.TextField(blank=True, null=True)),
                ('selectores_sugeridos', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fuente_web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.fuenteweb')),
            ],
            options={
                'verbose_name': 'sesion de laboratorio de mapeo',
                'verbose_name_plural': 'sesiones de laboratorio de mapeo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorioMapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_decimal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('url_producto', models.URLField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('seleccionado', models.BooleanField(default=False)),
                ('procesado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='oportunidades.sesionlaboratoriomapeo')),
            ],
            options={
                'verbose_name': 'resultado de laboratorio de mapeo',
                'verbose_name_plural': 'resultados de laboratorio de mapeo',
                'ordering': ['-score', 'id'],
            },
        ),
    ]
