# Generated by Django 5.0.14 on 2026-05-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0013_sesionlaboratoriomapeo_resultadolaboratoriomapeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciofuente',
            name='cuotas_texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preciofuente',
            name='precio_oportunidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='preciofuente',
            name='precio_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='preciofuente',
            name='precio_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='preciofuente',
            name='tipo_precio_oportunidad',
            field=models.CharField(choices=[('lista', 'Lista'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='cuotas_texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_lista_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_lista_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_oportunidad_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_tarjeta_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_tarjeta_texto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_transferencia_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='precio_transferencia_texto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='texto_precios_detectado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='tipo_precio_oportunidad',
            field=models.CharField(choices=[('lista', 'Lista'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='cuotas_texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_lista_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_lista_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_oportunidad_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_tarjeta_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_tarjeta_texto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_transferencia_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='precio_transferencia_texto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='texto_precios_detectado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='tipo_precio_oportunidad',
            field=models.CharField(choices=[('lista', 'Lista'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
