# Generated by Django 5.0.14 on 2026-06-02 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0014_preciofuente_cuotas_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofuente',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='hash_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='motivo_revision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='motivo_score_comercial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='score_comercial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='url_tecnica_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OperacionCuraduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('revisar', 'Revisar'), ('corregir', 'Corregir'), ('fusionar', 'Fusionar'), ('desvincular', 'Desvincular'), ('reasignar', 'Reasignar'), ('recalcular', 'Recalcular'), ('eliminar', 'Eliminar'), ('importar', 'Importar'), ('exportar', 'Exportar')], max_length=30)),
                ('descripcion', models.TextField()),
                ('datos_antes', models.TextField(blank=True, null=True)),
                ('datos_despues', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_texto', models.CharField(blank=True, max_length=150, null=True)),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
            ],
            options={
                'verbose_name': 'operacion de curaduria',
                'verbose_name_plural': 'operaciones de curaduria',
                'ordering': ['-fecha'],
            },
        ),
    ]
