# Generated by Django 5.0.14 on 2026-06-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0015_productofuente_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofuente',
            name='descartado_curaduria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='fecha_score_comercial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='fecha_ultima_curaduria',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='fusionado_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_fusionados', to='oportunidades.productofuente'),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='nivel_oportunidad',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('revisar', 'Revisar'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='nota_curaduria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CandidatoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('observado', 'Observado'), ('candidato', 'Candidato'), ('comprado', 'Comprado'), ('descartado', 'Descartado')], default='candidato', max_length=20)),
                ('precio_compra_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_reventa_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_margen_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto_fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_compra', to='oportunidades.productofuente')),
            ],
            options={
                'verbose_name': 'candidato de compra',
                'verbose_name_plural': 'candidatos de compra',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='DuplicadoIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicados_ignorados_a', to='oportunidades.productofuente')),
                ('producto_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicados_ignorados_b', to='oportunidades.productofuente')),
            ],
            options={
                'verbose_name': 'duplicado ignorado',
                'verbose_name_plural': 'duplicados ignorados',
                'ordering': ['-fecha'],
                'unique_together': {('producto_a', 'producto_b')},
            },
        ),
    ]
