# Generated by Django 5.0.14 on 2026-06-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0016_productofuente_descartado_curaduria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparacionprecio',
            name='cantidad_productos_fuente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparacionprecio',
            name='diferencia_pct_min_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='comparacionprecio',
            name='diferencia_pct_min_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='comparacionprecio',
            name='precio_maximo_oportunidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comparacionprecio',
            name='precio_minimo_oportunidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comparacionprecio',
            name='precio_promedio_oportunidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comparacionprecio',
            name='producto_fuente_mas_barato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparaciones_como_mas_barato', to='oportunidades.productofuente'),
        ),
        migrations.CreateModel(
            name='SugerenciaMatchingProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('descartar', 'Descartar')], default='descartar', max_length=20)),
                ('motivos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('ignorada', 'Ignorada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, null=True)),
                ('producto_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_matching_a', to='oportunidades.productofuente')),
                ('producto_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_matching_b', to='oportunidades.productofuente')),
                ('producto_canonico_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_matching', to='oportunidades.productocanonico')),
            ],
            options={
                'verbose_name': 'sugerencia de matching de producto',
                'verbose_name_plural': 'sugerencias de matching de productos',
                'ordering': ['-score', '-fecha_creacion'],
                'unique_together': {('producto_a', 'producto_b')},
            },
        ),
    ]
