# Generated by Django 5.0.14 on 2026-06-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0017_comparacionprecio_cantidad_productos_fuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofuente',
            name='fecha_demanda_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='motivo_demanda_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='nivel_demanda_actual',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('desconocida', 'Desconocida')], default='desconocida', max_length=20),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='score_demanda_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='nivel_demanda_preview',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('desconocida', 'Desconocida')], default='desconocida', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='score_demanda_preview',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='texto_demanda_detectado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='nivel_demanda_preview',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('desconocida', 'Desconocida')], default='desconocida', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='score_demanda_preview',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='texto_demanda_detectado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SenalDemandaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relevamiento', models.DateTimeField(auto_now_add=True)),
                ('cantidad_vendida_visible', models.PositiveIntegerField(default=0)),
                ('texto_vendidos', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_resenas', models.PositiveIntegerField(default=0)),
                ('cantidad_preguntas', models.PositiveIntegerField(default=0)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('etiqueta_mas_vendido', models.BooleanField(default=False)),
                ('etiqueta_destacado', models.BooleanField(default=False)),
                ('etiqueta_tendencia', models.BooleanField(default=False)),
                ('ranking_categoria', models.PositiveIntegerField(default=0)),
                ('stock_visible', models.PositiveIntegerField(default=0)),
                ('stock_anterior', models.PositiveIntegerField(default=0)),
                ('variacion_stock', models.IntegerField(default=0)),
                ('texto_stock', models.CharField(blank=True, max_length=200, null=True)),
                ('aparece_en_destacados', models.BooleanField(default=False)),
                ('aparece_en_promociones', models.BooleanField(default=False)),
                ('aparece_en_varias_fuentes', models.BooleanField(default=False)),
                ('cantidad_fuentes_donde_aparece', models.PositiveIntegerField(default=0)),
                ('recurrencia_en_previews', models.PositiveIntegerField(default=0)),
                ('score_demanda', models.PositiveIntegerField(default=0)),
                ('nivel_demanda', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('desconocida', 'Desconocida')], default='desconocida', max_length=20)),
                ('motivo_demanda', models.TextField(blank=True, null=True)),
                ('origen_dato', models.CharField(choices=[('directo', 'Directo'), ('estimado', 'Estimado'), ('manual', 'Manual'), ('calculado', 'Calculado')], default='estimado', max_length=20)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fuente_web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oportunidades.fuenteweb')),
                ('producto_fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senales_demanda', to='oportunidades.productofuente')),
            ],
            options={
                'verbose_name': 'senal de demanda de producto',
                'verbose_name_plural': 'senales de demanda de productos',
                'ordering': ['-fecha_relevamiento', '-id'],
            },
        ),
    ]
