# Generated by Django 5.0.14 on 2026-06-20 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0018_productofuente_fecha_demanda_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('extractor_web', 'Extractor web'), ('importacion_csv_excel', 'Importacion CSV/Excel'), ('carga_url', 'Carga URL'), ('manual', 'Manual'), ('api', 'API'), ('otro', 'Otro')], max_length=30)),
                ('tipo_carga', models.CharField(choices=[('prueba', 'Prueba'), ('piloto', 'Piloto'), ('real', 'Real'), ('historica', 'Historica'), ('descarte', 'Descarte')], default='piloto', max_length=20)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('ejecutando', 'Ejecutando'), ('procesado', 'Procesado'), ('procesado_con_errores', 'Procesado con errores'), ('validado', 'Validado'), ('descartado', 'Descartado'), ('error', 'Error')], default='creado', max_length=30)),
                ('url_origen', models.URLField(blank=True, null=True)),
                ('url_categoria', models.URLField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_relevamiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_texto', models.CharField(blank=True, max_length=150, null=True)),
                ('productos_detectados', models.PositiveIntegerField(default=0)),
                ('productos_seleccionados', models.PositiveIntegerField(default=0)),
                ('productos_procesados', models.PositiveIntegerField(default=0)),
                ('productos_creados', models.PositiveIntegerField(default=0)),
                ('productos_actualizados', models.PositiveIntegerField(default=0)),
                ('precios_creados', models.PositiveIntegerField(default=0)),
                ('senales_demanda_creadas', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('apto_dataset', models.BooleanField(default=True)),
                ('excluir_ml', models.BooleanField(default=False)),
                ('motivo_exclusion', models.TextField(blank=True, null=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('conector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_captura', to='oportunidades.conectorfuente')),
                ('ejecucion_conector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_captura', to='oportunidades.ejecucionconector')),
                ('extractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_captura', to='oportunidades.configuracionextractorweb')),
                ('fuente_web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_captura', to='oportunidades.fuenteweb')),
                ('importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_captura', to='oportunidades.importacionproductos')),
                ('sesion_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_captura', to='oportunidades.sesionlaboratoriomapeo')),
            ],
            options={
                'verbose_name': 'lote de captura',
                'verbose_name_plural': 'lotes de captura',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLoteCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('detectado', 'Detectado'), ('seleccionado', 'Seleccionado'), ('procesado', 'Procesado'), ('omitido', 'Omitido'), ('error', 'Error')], max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('datos_originales', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.preciofuente')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
                ('resultado_extraccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.resultadoextraccionweb')),
                ('resultado_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.resultadolaboratoriomapeo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='oportunidades.lotecaptura')),
            ],
            options={
                'verbose_name': 'detalle de lote de captura',
                'verbose_name_plural': 'detalles de lotes de captura',
                'ordering': ['lote', 'fecha', 'id'],
            },
        ),
        migrations.AddField(
            model_name='preciofuente',
            name='lote_captura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios', to='oportunidades.lotecaptura'),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='lote_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_origen', to='oportunidades.lotecaptura'),
        ),
        migrations.AddField(
            model_name='resultadoextraccionweb',
            name='lote_captura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_extraccion', to='oportunidades.lotecaptura'),
        ),
        migrations.AddField(
            model_name='resultadolaboratoriomapeo',
            name='lote_captura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_laboratorio', to='oportunidades.lotecaptura'),
        ),
        migrations.AddField(
            model_name='senaldemandaproducto',
            name='lote_captura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senales_demanda', to='oportunidades.lotecaptura'),
        ),
    ]
