# Generated by Django 5.0.14 on 2026-07-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0019_lotecaptura_detallelotecaptura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatocompra',
            name='fecha_decision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='fecha_deteccion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='fuente_precio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='lote_captura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas_compra', to='oportunidades.lotecaptura'),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='motivo_candidato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='motivo_descarte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='precio_oportunidad_detectado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='producto_canonico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas_compra', to='oportunidades.productocanonico'),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='score_comercial_detectado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='score_demanda_detectado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidatocompra',
            name='estado',
            field=models.CharField(choices=[('observado', 'Observado'), ('candidato', 'Candidato'), ('aprobado_compra', 'Aprobado para compra'), ('descartado', 'Descartado'), ('comprado', 'Comprado'), ('publicado', 'Publicado'), ('vendido_parcial', 'Vendido parcial'), ('vendido_total', 'Vendido total'), ('cancelado', 'Cancelado'), ('perdido', 'Perdido')], default='candidato', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatocompra',
            name='producto_fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas_compra', to='oportunidades.productofuente'),
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cantidad_comprada', models.PositiveIntegerField(default=1)),
                ('precio_unitario_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medio_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('comprobante_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('url_compra', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada'), ('devuelta', 'Devuelta')], default='confirmada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='oportunidades.candidatocompra')),
                ('fuente_web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.fuenteweb')),
                ('lote_captura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.lotecaptura')),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
            ],
            options={
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('marketplace', 'Marketplace'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('local', 'Local'), ('mercado_libre', 'Mercado Libre'), ('otro', 'Otro')], max_length=30)),
                ('titulo_publicacion', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('precio_publicado_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_publicada', models.PositiveIntegerField(default=1)),
                ('url_publicacion', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('pausada', 'Pausada'), ('vendida_parcial', 'Vendida parcial'), ('vendida_total', 'Vendida total'), ('cancelada', 'Cancelada')], default='publicada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.candidatocompra')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='oportunidades.compraproducto')),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
            ],
            options={
                'ordering': ['-fecha_publicacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoComercialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_comprada_total', models.PositiveIntegerField(default=0)),
                ('cantidad_vendida_total', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('inversion_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_neta_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_real_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio_promedio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_promedio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_hasta_primera_venta', models.PositiveIntegerField(blank=True, null=True)),
                ('dias_hasta_venta_total', models.PositiveIntegerField(blank=True, null=True)),
                ('estado_resultado', models.CharField(choices=[('sin_compra', 'Sin compra'), ('comprado_sin_vender', 'Comprado sin vender'), ('venta_parcial', 'Venta parcial'), ('vendido_con_ganancia', 'Vendido con ganancia'), ('vendido_sin_ganancia', 'Vendido sin ganancia'), ('vendido_con_perdida', 'Vendido con perdida'), ('descartado', 'Descartado')], default='sin_compra', max_length=30)),
                ('aprendizaje', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_comercial', to='oportunidades.candidatocompra')),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('cantidad_vendida', models.PositiveIntegerField(default=1)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingreso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_envio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_costos_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_neta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('canal_venta', models.CharField(choices=[('marketplace', 'Marketplace'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('local', 'Local'), ('mercado_libre', 'Mercado Libre'), ('otro', 'Otro')], max_length=30)),
                ('comprador_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('devuelta', 'Devuelta')], default='confirmada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.candidatocompra')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='oportunidades.compraproducto')),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidades.productofuente')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='oportunidades.publicacionreventa')),
            ],
            options={
                'ordering': ['-fecha_venta', '-id'],
            },
        ),
    ]
