# Generated by Django 5.0.14 on 2026-07-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0020_candidatocompra_fecha_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionRadarTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto_original', models.TextField()),
                ('origen', models.CharField(choices=[('chatgpt_radar', 'ChatGPT Radar'), ('texto_externo', 'Texto externo'), ('manual', 'Manual')], default='chatgpt_radar', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('analizada', 'Analizada'), ('importada', 'Importada'), ('importada_con_advertencias', 'Importada con advertencias'), ('error', 'Error'), ('descartada', 'Descartada')], default='pendiente', max_length=40)),
                ('oportunidades_detectadas', models.PositiveIntegerField(default=0)),
                ('oportunidades_importadas', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'importacion radar texto',
                'verbose_name_plural': 'importaciones radar texto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='origen_candidato',
            field=models.CharField(choices=[('ranking', 'Ranking'), ('radar_texto', 'Radar texto'), ('manual', 'Manual')], default='ranking', max_length=30),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='producto_texto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidatocompra',
            name='tienda_texto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='OportunidadRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('tienda', models.CharField(blank=True, max_length=150, null=True)),
                ('producto_nombre', models.CharField(max_length=250)),
                ('marca', models.CharField(blank=True, max_length=150, null=True)),
                ('modelo', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria_texto', models.CharField(blank=True, max_length=150, null=True)),
                ('rubro', models.CharField(blank=True, max_length=150, null=True)),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_comparable_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_comparable_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_historico_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descuento_real_pct_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descuento_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_lista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_transferencia_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_tarjeta_cuotas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cuotas_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('comparable_principal_tienda', models.CharField(blank=True, max_length=150, null=True)),
                ('comparable_principal_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comparables_texto', models.TextField(blank=True, null=True)),
                ('envio_texto', models.CharField(blank=True, max_length=250, null=True)),
                ('stock_texto', models.CharField(blank=True, max_length=250, null=True)),
                ('vendedor_texto', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion_texto', models.CharField(blank=True, max_length=250, null=True)),
                ('motivo_conveniencia', models.TextField(blank=True, null=True)),
                ('chequeo_antimarketing', models.TextField(blank=True, null=True)),
                ('riesgo_texto', models.TextField(blank=True, null=True)),
                ('decision_sugerida', models.CharField(choices=[('comprar', 'Comprar'), ('analizar', 'Analizar'), ('esperar', 'Esperar'), ('descartar', 'Descartar')], default='analizar', max_length=20)),
                ('score_radar', models.PositiveIntegerField(default=0)),
                ('nivel_oportunidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('dudosa', 'Dudosa')], default='dudosa', max_length=20)),
                ('requiere_revision', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('chatgpt_radar', 'ChatGPT Radar'), ('manual', 'Manual'), ('texto_externo', 'Texto externo'), ('otro', 'Otro')], default='chatgpt_radar', max_length=30)),
                ('texto_original', models.TextField()),
                ('texto_parseado', models.TextField(blank=True, null=True)),
                ('url_oferta', models.URLField(blank=True, null=True)),
                ('url_comparable', models.URLField(blank=True, null=True)),
                ('fecha_detectada', models.DateTimeField(auto_now_add=True)),
                ('fecha_oferta_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('detectada', 'Detectada'), ('importada', 'Importada'), ('revisada', 'Revisada'), ('vinculada', 'Vinculada'), ('candidata', 'Candidata'), ('descartada', 'Descartada')], default='importada', max_length=20)),
                ('apta_dataset', models.BooleanField(default=True)),
                ('excluir_ml', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('candidato_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_radar', to='oportunidades.candidatocompra')),
                ('fuente_web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_radar', to='oportunidades.fuenteweb')),
                ('importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='oportunidades.importacionradartexto')),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_radar', to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_radar', to='oportunidades.productofuente')),
            ],
            options={
                'verbose_name': 'oportunidad radar',
                'verbose_name_plural': 'oportunidades radar',
                'ordering': ['-fecha_detectada', '-score_radar'],
            },
        ),
    ]
