# Generated by Django 5.0.14 on 2026-07-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0021_importacionradartexto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainteres',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='oportunidades.categoriainteres'),
        ),
        migrations.AddField(
            model_name='categoriainteres',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriainteres',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoriainteres',
            name='marcas_clave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriainteres',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriainteres',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='categoria_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='etiquetas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productofuente',
            name='subcategoria_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
