# Generated by Django 5.0.14 on 2026-07-18 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0023_categorias_base_normalizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo_ranking', models.CharField(choices=[('alta_venta', 'Productos con senales de alta venta'), ('obra_hogar', 'Ofertas de obra/hogar'), ('supermercado_consumo', 'Supermercado/consumo'), ('supermercado_reventa', 'Supermercado/reventa')], default='alta_venta', max_length=40)),
                ('alcance', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_referencia', models.DateField()),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(default='Radar ChatGPT - carga manual', max_length=180)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('cantidad_filas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validado', 'Validado'), ('publicado', 'Publicado'), ('descartado', 'Descartado')], default='borrador', max_length=20)),
                ('hash_importacion', models.CharField(db_index=True, max_length=64)),
                ('texto_original', models.TextField(blank=True, null=True)),
                ('posible_duplicado', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_ranking', to='oportunidades.categoriainteres')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lote de ranking',
                'verbose_name_plural': 'lotes de ranking',
                'ordering': ['-fecha_referencia', '-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('nombre_original', models.CharField(max_length=255)),
                ('subcategoria', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('tienda', models.CharField(blank=True, max_length=150, null=True)),
                ('texto_senal', models.TextField(blank=True, null=True)),
                ('tipo_senal', models.CharField(choices=[('etiqueta_mas_vendido', 'Etiqueta mas vendido'), ('ranking_oficial', 'Ranking oficial'), ('bloque_destacado', 'Bloque destacado'), ('busqueda_destacada', 'Busqueda destacada'), ('alta_recurrencia', 'Alta recurrencia'), ('radar_chatgpt', 'Radar ChatGPT'), ('carga_manual', 'Carga manual'), ('otra', 'Otra')], default='carga_manual', max_length=40)),
                ('url_evidencia', models.URLField(blank=True, null=True)),
                ('tipo_evidencia', models.CharField(choices=[('ficha_producto', 'Ficha de producto'), ('listado_productos', 'Listado de productos'), ('pagina_categoria', 'Pagina de categoria'), ('ranking_tienda', 'Ranking de tienda'), ('folleto', 'Folleto'), ('catalogo', 'Catalogo'), ('pdf', 'PDF'), ('otra', 'Otra')], default='otra', max_length=40)),
                ('fecha_observacion', models.DateField(blank=True, null=True)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('evidencia_insuficiente', 'Evidencia insuficiente'), ('descartado', 'Descartado')], default='pendiente', max_length=40)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('posicion_anterior', models.PositiveIntegerField(blank=True, null=True)),
                ('variacion_posiciones', models.IntegerField(default=0)),
                ('tendencia', models.CharField(choices=[('nuevo', 'Nuevo'), ('subio', 'Subio'), ('bajo', 'Bajo'), ('se_mantuvo', 'Se mantuvo'), ('sin_comparacion', 'Sin comparacion')], default='sin_comparacion', max_length=40)),
                ('apariciones_ultimos_lotes', models.PositiveIntegerField(default=1)),
                ('primera_fecha_observada', models.DateField(blank=True, null=True)),
                ('ultima_fecha_observada', models.DateField(blank=True, null=True)),
                ('evidencia_es_ficha_exacta', models.BooleanField(default=False)),
                ('coincidencia_confianza', models.PositiveIntegerField(default=0)),
                ('coincidencia_mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_presentacion', models.CharField(choices=[('individual', 'Individual'), ('pack', 'Pack'), ('fardo', 'Fardo'), ('bulto', 'Bulto'), ('promocion', 'Promocion')], default='individual', max_length=20)),
                ('unidades_por_presentacion', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('contenido_neto_por_unidad', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unidad_medida_original', models.CharField(choices=[('ml', 'ml'), ('litro', 'litro'), ('g', 'g'), ('kg', 'kg'), ('unidad', 'unidad')], default='unidad', max_length=20)),
                ('presentaciones_incluidas', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidades_totales', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('contenido_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('precio_final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_envio_traslado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_final_puesto_salta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_por_litro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_por_100', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_promocion', models.CharField(choices=[('ninguna', 'Sin promocion'), ('2x1', '2x1'), ('3x2', '3x2'), ('segunda_descuento', 'Segunda unidad con descuento'), ('descuento_directo', 'Descuento directo'), ('descuento_bancario', 'Descuento bancario'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('personalizada', 'Personalizada')], default='ninguna', max_length=40)),
                ('cantidad_total_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_pagada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_reventa_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_efectivo_por_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_bruto_estimado_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_porcentual_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cantidad_minima_bulto', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_por_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('rotacion', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('sin_determinar', 'Sin determinar')], default='sin_determinar', max_length=30)),
                ('conveniencia', models.CharField(choices=[('consumo_propio', 'Conveniente para consumo propio'), ('reventa', 'Posible oportunidad de reventa'), ('ambas', 'Consumo y reventa'), ('sin_determinar', 'Sin determinar')], default='sin_determinar', max_length=30)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_ranking', to='oportunidades.categoriainteres')),
                ('fuente_web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_ranking', to='oportunidades.fuenteweb')),
                ('producto_canonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_ranking', to='oportunidades.productocanonico')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_ranking', to='oportunidades.productofuente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oportunidades.loteranking')),
            ],
            options={
                'verbose_name': 'item de ranking',
                'verbose_name_plural': 'items de ranking',
                'ordering': ['lote', 'posicion', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='loteranking',
            index=models.Index(fields=['tipo_ranking', 'alcance', 'fecha_referencia'], name='oportunidad_tipo_ra_1c1e36_idx'),
        ),
        migrations.AddIndex(
            model_name='loteranking',
            index=models.Index(fields=['estado', 'fecha_referencia'], name='oportunidad_estado_bef366_idx'),
        ),
        migrations.AddIndex(
            model_name='itemranking',
            index=models.Index(fields=['lote', 'posicion'], name='oportunidad_lote_id_3d0975_idx'),
        ),
        migrations.AddIndex(
            model_name='itemranking',
            index=models.Index(fields=['tienda', 'categoria'], name='oportunidad_tienda_d1166b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemranking',
            index=models.Index(fields=['tendencia'], name='oportunidad_tendenc_865a57_idx'),
        ),
    ]
