# Generated by Django 5.0.14 on 2026-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0024_loteranking_itemranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemranking',
            name='precio_por_metro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
