from django.shortcuts import redirect
from django.urls import path

from . import views


app_name = "oportunidades"

urlpatterns = [
    path("", lambda request: redirect("oportunidades:lista"), name="inicio"),
    path("oportunidades/", views.lista_oportunidades, name="lista"),
    path("oportunidades/<int:pk>/", views.detalle_oportunidad, name="detalle"),
    path("oportunidades/<int:pk>/estado/<str:nuevo_estado>/", views.cambiar_estado_oportunidad, name="cambiar_estado"),
    path("oportunidades/<int:pk>/recalcular/", views.recalcular_oportunidad, name="recalcular"),
    path("oportunidades/<int:pk>/generar-contenido/", views.generar_contenido_oportunidad, name="generar_contenido"),
    path("mercadolibre/buscar/", views.buscar_mercado_libre, name="buscar_meli"),
    path("mercadolibre/oauth/iniciar/", views.oauth_iniciar, name="oauth_iniciar"),
    path("mercadolibre/oauth/callback/", views.oauth_callback, name="oauth_callback"),
    path("mercadolibre/oauth/diagnostico/", views.oauth_diagnostico, name="oauth_diagnostico"),
    path("mercadolibre/diagnostico-endpoints/", views.diagnostico_endpoints_meli, name="diagnostico_endpoints_meli"),
    path("laboratorio/mapeo-web/", views.laboratorio_mapeo_web, name="laboratorio_mapeo_web"),
    path("laboratorio/mapeo-web/ayuda/", views.laboratorio_ayuda, name="laboratorio_ayuda"),
    path("laboratorio/mapeo-web/ajustar/", views.laboratorio_ajustar, name="laboratorio_ajustar"),
    path("laboratorio/mapeo-web/<int:sesion_id>/", views.laboratorio_sesion, name="laboratorio_sesion"),
    path("laboratorio/mapeo-web/<int:sesion_id>/guardar-extractor/", views.laboratorio_guardar_extractor, name="laboratorio_guardar_extractor"),
    path("laboratorio/mapeo-web/<int:sesion_id>/procesar-seleccionados/", views.laboratorio_procesar_seleccionados, name="laboratorio_procesar_seleccionados"),
    path("laboratorio/mapeo-web/resultados/<int:resultado_id>/seleccionar/", views.laboratorio_seleccionar_resultado, name="laboratorio_seleccionar_resultado"),
    path("fuentes/", views.lista_fuentes, name="lista_fuentes"),
    path("fuentes/nueva-rapida/", views.nueva_fuente_rapida, name="nueva_fuente_rapida"),
    path("fuentes/wizard/nueva/", views.wizard_nueva_fuente, name="wizard_nueva_fuente"),
    path("fuentes/estado-operativo/", views.estado_operativo_fuentes, name="estado_operativo_fuentes"),
    path("fuentes/gangahome/preparar/", views.preparar_gangahome_view, name="preparar_gangahome"),
    path("fuentes/<int:pk>/", views.detalle_fuente, name="detalle_fuente"),
    path("fuentes/<int:pk>/estado-operativo/", views.estado_operativo_fuente, name="estado_operativo_fuente"),
    path("fuentes/<int:pk>/wizard/auditoria/", views.wizard_auditoria_fuente, name="wizard_auditoria_fuente"),
    path("fuentes/<int:pk>/wizard/revision/", views.wizard_revision_fuente, name="wizard_revision_fuente"),
    path("fuentes/<int:pk>/wizard/conector/", views.wizard_conector_fuente, name="wizard_conector_fuente"),
    path("fuentes/<int:pk>/wizard/extractor/", views.wizard_extractor_fuente, name="wizard_extractor_fuente"),
    path("fuentes/<int:pk>/wizard/preview/", views.wizard_preview_fuente, name="wizard_preview_fuente"),
    path("fuentes/<int:pk>/wizard/procesar/", views.wizard_procesar_fuente, name="wizard_procesar_fuente"),
    path("fuentes/<int:pk>/auditar/", views.auditar_fuente_view, name="auditar_fuente"),
    path("fuentes/<int:pk>/revisiones-manuales/", views.lista_revisiones_fuente, name="lista_revisiones_fuente"),
    path("fuentes/<int:pk>/revision-manual/nueva/", views.nueva_revision_fuente, name="nueva_revision_fuente"),
    path("fuentes/decohome/preparar/", views.preparar_decohome_view, name="preparar_decohome"),
    path("fuentes/decohome/auditar/", views.auditar_decohome_view, name="auditar_decohome"),
    path("fuentes/decohome/selectores/", views.selectores_decohome, name="selectores_decohome"),
    path("fuentes/decohome/estado-operativo/", views.estado_operativo_decohome, name="estado_operativo_decohome"),
    path("fuentes/decohome/laboratorio/", views.laboratorio_decohome, name="laboratorio_decohome"),
    path("fuentes/<int:fuente_id>/laboratorio/", views.laboratorio_mapeo_web, name="laboratorio_fuente"),
    path("decisiones-tecnicas/", views.lista_decisiones_tecnicas, name="lista_decisiones_tecnicas"),
    path("auditorias-fuentes/", views.lista_auditorias_fuentes, name="lista_auditorias_fuentes"),
    path("auditorias-fuentes/<int:pk>/", views.detalle_auditoria_fuente, name="detalle_auditoria_fuente"),
    path("auditorias-fuentes/<int:pk>/aplicar-politica/", views.aplicar_politica_auditoria, name="aplicar_politica_auditoria"),
    path("scraping/politica/", views.politica_scraping, name="politica_scraping"),
    path("extractores/", views.lista_extractores, name="lista_extractores"),
    path("extractores/resultados-pendientes/", views.resultados_pendientes_extractores, name="resultados_pendientes_extractores"),
    path("extractores/<int:pk>/", views.detalle_extractor, name="detalle_extractor"),
    path("extractores/<int:pk>/editar/", views.editar_extractor, name="editar_extractor"),
    path(
        "extractores/<int:pk>/habilitar-preview-controlado/",
        views.habilitar_preview_controlado_extractor,
        name="habilitar_preview_controlado_extractor",
    ),
    path("extractores/<int:pk>/selectores/", views.selectores_extractor, name="selectores_extractor"),
    path("extractores/<int:pk>/probar-selectores/", views.probar_selectores_extractor, name="probar_selectores_extractor"),
    path("extractores/<int:pk>/resultados/", views.resultados_extractor, name="resultados_extractor"),
    path("extractores/<int:pk>/seleccionar-mejores/", views.seleccionar_mejores_extractor, name="seleccionar_mejores_extractor"),
    path("extractores/resultados/<int:resultado_id>/seleccionar/", views.seleccionar_resultado_extractor, name="seleccionar_resultado_extractor"),
    path("extractores/<int:pk>/limpiar-seleccion/", views.limpiar_seleccion_extractor, name="limpiar_seleccion_extractor"),
    path("extractores/<int:pk>/seleccionar-procesables/", views.seleccionar_todos_procesables_extractor, name="seleccionar_todos_procesables_extractor"),
    path("extractores/<int:pk>/confirmar-procesamiento/", views.confirmar_procesamiento_extractor, name="confirmar_procesamiento_extractor"),
    path("extractores/<int:pk>/procesar-seleccionados/", views.procesar_seleccionados_extractor, name="procesar_seleccionados_extractor"),
    path("extractores/<int:pk>/diagnostico-js/", views.diagnostico_js_extractor, name="diagnostico_js_extractor"),
    path("extractores/<int:pk>/preview/", views.preview_extractor, name="preview_extractor"),
    path("extractores/<int:pk>/procesar/", views.procesar_extractor, name="procesar_extractor"),
    path("importaciones/", views.lista_importaciones, name="lista_importaciones"),
    path("importaciones/nueva/", views.nueva_importacion, name="nueva_importacion"),
    path("importaciones/plantilla-csv/", views.descargar_plantilla_importacion, name="plantilla_importacion_csv"),
    path("importaciones/<int:pk>/", views.detalle_importacion, name="detalle_importacion"),
    path("importaciones/<int:pk>/procesar/", views.procesar_importacion_view, name="procesar_importacion"),
    path("productos/cargar-url/", views.cargar_producto_url, name="cargar_producto_url"),
    path("productos-multifuente/", views.lista_productos_multifuente, name="lista_productos_multifuente"),
    path("productos-multifuente/<int:pk>/", views.detalle_producto_multifuente, name="detalle_producto_multifuente"),
    path("productos-multifuente/<int:pk>/desvincular/<int:producto_fuente_id>/", views.desvincular_producto_multifuente, name="desvincular_producto_multifuente"),
    path("matching/productos/", views.matching_productos, name="matching_productos"),
    path("matching/productos/<int:pk>/", views.matching_producto_detalle, name="matching_producto_detalle"),
    path("matching/productos/<int:pk>/aceptar/", views.matching_producto_aceptar, name="matching_producto_aceptar"),
    path("matching/productos/<int:pk>/rechazar/", views.matching_producto_rechazar, name="matching_producto_rechazar"),
    path("matching/productos/<int:pk>/ignorar/", views.matching_producto_ignorar, name="matching_producto_ignorar"),
    path("curaduria/productos/", views.curaduria_productos, name="curaduria_productos"),
    path("curaduria/productos/accion-masiva/", views.curaduria_productos_accion_masiva, name="curaduria_productos_accion_masiva"),
    path("curaduria/dashboard/", views.curaduria_dashboard, name="curaduria_dashboard"),
    path("curaduria/duplicados/", views.curaduria_duplicados, name="curaduria_duplicados"),
    path("curaduria/duplicados/<int:producto_a_id>/<int:producto_b_id>/fusionar/", views.fusionar_duplicados_view, name="fusionar_duplicados"),
    path("curaduria/duplicados/<int:producto_a_id>/<int:producto_b_id>/ignorar/", views.ignorar_duplicado_view, name="ignorar_duplicado"),
    path("curaduria/productos/<int:pk>/", views.detalle_curaduria_producto, name="detalle_curaduria_producto"),
    path("curaduria/productos/<int:pk>/editar/", views.editar_curaduria_producto, name="editar_curaduria_producto"),
    path("curaduria/productos/<int:pk>/editar-precio/", views.editar_precio_curaduria_producto, name="editar_precio_curaduria_producto"),
    path("curaduria/productos/<int:pk>/marcar-revision/", views.marcar_revision_producto, name="marcar_revision_producto"),
    path("curaduria/productos/<int:pk>/marcar-revisado/", views.marcar_revisado_producto, name="marcar_revisado_producto"),
    path("curaduria/productos/<int:pk>/reasignar-canonico/", views.reasignar_canonico_producto, name="reasignar_canonico_producto"),
    path("curaduria/previews/", views.curaduria_previews, name="curaduria_previews"),
    path("curaduria/previews/<int:pk>/reprocesar/", views.reprocesar_preview, name="reprocesar_preview"),
    path("curaduria/previews/<int:pk>/actualizar-producto/", views.actualizar_producto_desde_preview_view, name="actualizar_producto_desde_preview"),
    path("curaduria/previews/<int:pk>/desvincular/", views.desvincular_preview_view, name="desvincular_preview"),
    path("dataset/exportar/", views.dataset_exportar, name="dataset_exportar"),
    path("lotes-captura/", views.lotes_captura_lista, name="lotes_captura_lista"),
    path("lotes-captura/<int:pk>/", views.lote_captura_detalle, name="lote_captura_detalle"),
    path("lotes-captura/<int:pk>/exportar/", views.lote_captura_exportar, name="lote_captura_exportar"),
    path("lotes-captura/<int:pk>/<str:accion>/", views.lote_captura_accion, name="lote_captura_accion"),
    path("dataset/backup/", views.dataset_backup, name="dataset_backup"),
    path("dataset/validacion-piloto/", views.dataset_validacion_piloto, name="dataset_validacion_piloto"),
    path("sistema/base-datos/", views.diagnostico_base_datos, name="diagnostico_base_datos"),
    path("oportunidades/ranking/", views.ranking_oportunidades, name="ranking_oportunidades"),
    path("oportunidades/ranking/<int:pk>/candidato/", views.marcar_candidato_compra, name="marcar_candidato_compra"),
    path("oportunidades/ranking/<int:pk>/descartar/", views.descartar_candidato_compra, name="descartar_candidato_compra"),
    path("rankings/", views.rankings_lista, name="rankings_lista"),
    path("rankings/supermercado/", views.rankings_supermercado, name="rankings_supermercado"),
    path("rankings/importar/", views.ranking_importar, name="ranking_importar"),
    path("rankings/lotes/<int:pk>/", views.ranking_lote_detalle, name="ranking_lote_detalle"),
    path("rankings/items/<int:pk>/historico/", views.ranking_item_historico, name="ranking_item_historico"),
    path("oportunidades/candidatos-compra/", views.candidatos_compra, name="candidatos_compra"),
    path("comercial/dashboard/", views.comercial_dashboard, name="comercial_dashboard"),
    path("comercial/candidatos/", views.candidatos_compra, name="comercial_candidatos"),
    path("comercial/candidatos/crear/<int:producto_fuente_id>/", views.comercial_candidato_crear, name="comercial_candidato_crear"),
    path("comercial/candidatos/<int:pk>/", views.comercial_candidato_detalle, name="comercial_candidato_detalle"),
    path("comercial/candidatos/<int:pk>/aprobar/", views.comercial_candidato_aprobar, name="comercial_candidato_aprobar"),
    path("comercial/candidatos/<int:pk>/descartar/", views.comercial_candidato_descartar, name="comercial_candidato_descartar"),
    path("comercial/candidatos/<int:pk>/registrar-compra/", views.comercial_registrar_compra, name="comercial_registrar_compra"),
    path("comercial/compras/<int:pk>/registrar-publicacion/", views.comercial_registrar_publicacion, name="comercial_registrar_publicacion"),
    path("comercial/compras/<int:pk>/registrar-venta/", views.comercial_registrar_venta, name="comercial_registrar_venta"),
    path("comercial/candidatos/<int:pk>/recalcular/", views.comercial_recalcular_resultado, name="comercial_recalcular_resultado"),
    path("radar/dashboard/", views.radar_dashboard, name="radar_dashboard"),
    path("radar/ofertas/", views.radar_ofertas, name="radar_ofertas"),
    path("radar/ofertas/<int:pk>/", views.radar_oferta_detalle, name="radar_oferta_detalle"),
    path("radar/ofertas/<int:pk>/editar/", views.radar_oferta_editar, name="radar_oferta_editar"),
    path("radar/ofertas/<int:pk>/marcar-revisada/", views.radar_oferta_marcar_revisada, name="radar_oferta_marcar_revisada"),
    path("radar/ofertas/<int:pk>/descartar/", views.radar_oferta_descartar, name="radar_oferta_descartar"),
    path("radar/ofertas/<int:pk>/marcar-candidato/", views.radar_oferta_marcar_candidato, name="radar_oferta_marcar_candidato"),
    path("radar/importar-texto/", views.radar_importar_texto, name="radar_importar_texto"),
    path("radar/importaciones/<int:pk>/", views.radar_importacion_detalle, name="radar_importacion_detalle"),
    path("radar/importaciones/<int:pk>/importar/", views.radar_importacion_importar, name="radar_importacion_importar"),
    path("radar/importaciones/<int:pk>/descartar/", views.radar_importacion_descartar, name="radar_importacion_descartar"),
    path("demanda/dashboard/", views.demanda_dashboard, name="demanda_dashboard"),
    path("demanda/productos/", views.demanda_productos, name="demanda_productos"),
    path("demanda/productos/<int:producto_fuente_id>/", views.demanda_producto_detalle, name="demanda_producto_detalle"),
    path("demanda/productos/<int:producto_fuente_id>/recalcular/", views.demanda_producto_recalcular, name="demanda_producto_recalcular"),
    path("demanda/productos/<int:producto_fuente_id>/editar-senales/", views.demanda_producto_editar_senales, name="demanda_producto_editar_senales"),
    path("storage/diagnostico/", views.diagnostico_storage, name="diagnostico_storage"),
    path("conectores/", views.lista_conectores, name="lista_conectores"),
    path("conectores/nuevo-catalogo/", views.nuevo_conector_catalogo, name="nuevo_conector_catalogo"),
    path("conectores/<int:pk>/", views.detalle_conector, name="detalle_conector"),
    path("conectores/<int:pk>/validar/", views.validar_conector, name="validar_conector"),
    path("conectores/<int:pk>/ejecutar/", views.ejecutar_conector, name="ejecutar_conector"),
    path(
        "productos-multifuente/<int:pk>/recalcular-comparacion/",
        views.recalcular_comparacion_multifuente,
        name="recalcular_comparacion_multifuente",
    ),
    path(
        "productos-multifuente/<int:pk>/recalcular-evaluacion/",
        views.recalcular_evaluacion_multifuente,
        name="recalcular_evaluacion_multifuente",
    ),
    path("api/oportunidades/", views.OportunidadListAPIView.as_view(), name="api_lista"),
    path("api/ofertas/", views.OportunidadListAPIView.as_view(), name="api_ofertas"),
    path("api/oportunidades/<int:pk>/", views.OportunidadDetailAPIView.as_view(), name="api_detalle"),
    path("api/oportunidades/<int:pk>/estado/", views.OportunidadEstadoAPIView.as_view(), name="api_estado"),
    path("api/oportunidades/<int:pk>/recalcular/", views.OportunidadRecalcularAPIView.as_view(), name="api_recalcular"),
    path(
        "api/oportunidades/<int:pk>/generar-contenido/",
        views.OportunidadGenerarContenidoAPIView.as_view(),
        name="api_generar_contenido",
    ),
    path("api/meli/buscar/", views.MeliBuscarAPIView.as_view(), name="api_meli_buscar"),
    path("api/meli/sincronizar/", views.MeliSincronizarAPIView.as_view(), name="api_meli_sincronizar"),
    path("api/meli/consultas/", views.MeliConsultasAPIView.as_view(), name="api_meli_consultas"),
    path("api/fuentes/", views.FuenteWebListAPIView.as_view(), name="api_fuentes"),
    path("api/fuentes/estado-operativo/", views.FuenteEstadoOperativoListAPIView.as_view(), name="api_fuentes_estado_operativo"),
    path("api/fuentes/<int:pk>/", views.FuenteWebDetailAPIView.as_view(), name="api_fuente_detalle"),
    path("api/fuentes/<int:pk>/estado/", views.FuenteEstadoOperativoAPIView.as_view(), name="api_fuente_estado_operativo"),
    path("api/fuentes/<int:pk>/preview/", views.FuentePreviewAPIView.as_view(), name="api_fuente_preview"),
    path("api/fuentes/<int:pk>/laboratorio/analizar/", views.FuenteLaboratorioAnalizarAPIView.as_view(), name="api_fuente_laboratorio_analizar"),
    path("api/decisiones-tecnicas/", views.DecisionTecnicaListAPIView.as_view(), name="api_decisiones_tecnicas"),
    path("api/categorias/", views.CategoriaInteresListAPIView.as_view(), name="api_categorias"),
    path("api/productos-canonicos/", views.ProductoCanonicoListAPIView.as_view(), name="api_productos_canonicos"),
    path("api/productos-fuente/", views.ProductoFuenteListAPIView.as_view(), name="api_productos_fuente"),
    path("api/productos/", views.ProductoFuenteListAPIView.as_view(), name="api_productos"),
    path("api/rankings/lotes/", views.LoteRankingListAPIView.as_view(), name="api_rankings_lotes"),
    path("api/rankings/lotes/<int:lote_id>/items/", views.ItemRankingListAPIView.as_view(), name="api_rankings_lote_items"),
    path("api/rankings/items/", views.ItemRankingListAPIView.as_view(), name="api_rankings_items"),
    path("api/rankings/actual/", views.RankingActualAPIView.as_view(), name="api_rankings_actual"),
    path("api/rankings/items/<int:pk>/historico/", views.ItemRankingHistoricoAPIView.as_view(), name="api_rankings_item_historico"),
    path("api/importaciones/", views.ImportacionProductosListCreateAPIView.as_view(), name="api_importaciones"),
    path("api/importaciones/<int:pk>/", views.ImportacionProductosDetailAPIView.as_view(), name="api_importacion_detalle"),
    path(
        "api/importaciones/<int:pk>/procesar/",
        views.ImportacionProductosProcesarAPIView.as_view(),
        name="api_importacion_procesar",
    ),
    path("api/productos-multifuente/", views.ProductoMultifuenteListAPIView.as_view(), name="api_productos_multifuente"),
    path(
        "api/productos-multifuente/<int:pk>/",
        views.ProductoMultifuenteDetailAPIView.as_view(),
        name="api_producto_multifuente_detalle",
    ),
    path("api/productos/cargar-url/", views.CargaProductoURLAPIView.as_view(), name="api_cargar_producto_url"),
    path("api/conectores/", views.ConectorFuenteListAPIView.as_view(), name="api_conectores"),
    path("api/conectores/catalogo/", views.ConectorCatalogoCreateAPIView.as_view(), name="api_conector_catalogo"),
    path("api/conectores/<int:pk>/", views.ConectorFuenteDetailAPIView.as_view(), name="api_conector_detalle"),
    path("api/conectores/<int:pk>/validar/", views.ConectorFuenteValidarAPIView.as_view(), name="api_conector_validar"),
    path("api/conectores/<int:pk>/ejecutar/", views.ConectorFuenteEjecutarAPIView.as_view(), name="api_conector_ejecutar"),
    path("api/ejecuciones-conector/", views.EjecucionConectorListAPIView.as_view(), name="api_ejecuciones_conector"),
    path(
        "api/ejecuciones-conector/<int:pk>/",
        views.EjecucionConectorDetailAPIView.as_view(),
        name="api_ejecucion_conector_detalle",
    ),
    path("api/auditorias-fuentes/", views.AuditoriaFuenteWebListAPIView.as_view(), name="api_auditorias_fuentes"),
    path("api/auditorias-fuentes/<int:pk>/", views.AuditoriaFuenteWebDetailAPIView.as_view(), name="api_auditoria_fuente_detalle"),
    path("api/fuentes/<int:pk>/auditar/", views.FuenteAuditarAPIView.as_view(), name="api_auditar_fuente"),
    path("api/revisiones-manuales/", views.RevisionManualFuenteListAPIView.as_view(), name="api_revisiones_manuales"),
    path("api/fuentes/<int:pk>/revision-manual/", views.FuenteRevisionManualCreateAPIView.as_view(), name="api_revision_manual_fuente"),
    path("api/fuentes/wizard/nueva/", views.FuenteWizardNuevaAPIView.as_view(), name="api_wizard_nueva_fuente"),
    path("api/fuentes/generica/preparar/", views.FuenteGenericaPrepararAPIView.as_view(), name="api_preparar_fuente_generica"),
    path("api/fuentes/decohome/preparar/", views.DecoHomePrepararAPIView.as_view(), name="api_preparar_decohome"),
    path("api/fuentes/decohome/auditar/", views.DecoHomeAuditarAPIView.as_view(), name="api_auditar_decohome"),
    path("api/extractores/", views.ConfiguracionExtractorWebListAPIView.as_view(), name="api_extractores"),
    path("api/extractores/<int:pk>/", views.ConfiguracionExtractorWebDetailAPIView.as_view(), name="api_extractor_detalle"),
    path("api/extractores/<int:pk>/selectores/", views.ExtractorSelectoresAPIView.as_view(), name="api_extractor_selectores"),
    path("api/extractores/<int:pk>/probar-selectores/", views.ExtractorProbarSelectoresAPIView.as_view(), name="api_extractor_probar_selectores"),
    path("api/extractores/<int:pk>/resultados/", views.ExtractorResultadosAPIView.as_view(), name="api_extractor_resultados"),
    path("api/extractores/resultados-pendientes/", views.ExtractorResultadosPendientesAPIView.as_view(), name="api_extractor_resultados_pendientes"),
    path("api/extractores/resultados/<int:resultado_id>/seleccionar/", views.ResultadoSeleccionarAPIView.as_view(), name="api_resultado_seleccionar"),
    path("api/extractores/<int:pk>/seleccionar-mejores/", views.ExtractorSeleccionarMejoresAPIView.as_view(), name="api_extractor_seleccionar_mejores"),
    path("api/extractores/<int:pk>/procesar-seleccionados/", views.ExtractorProcesarSeleccionadosAPIView.as_view(), name="api_extractor_procesar_seleccionados"),
    path("api/extractores/<int:pk>/diagnostico-js/", views.ExtractorDiagnosticoJSAPIView.as_view(), name="api_extractor_diagnostico_js"),
    path("api/extractores/<int:pk>/diagnostico-headless/", views.ExtractorDiagnosticoHeadlessAPIView.as_view(), name="api_extractor_diagnostico_headless"),
    path("api/extractores/<int:pk>/preview/", views.ExtractorPreviewAPIView.as_view(), name="api_extractor_preview"),
    path("api/extractores/<int:pk>/procesar/", views.ExtractorProcesarAPIView.as_view(), name="api_extractor_procesar"),
    path("api/laboratorio/mapeo-web/analizar/", views.LaboratorioAnalizarAPIView.as_view(), name="api_laboratorio_analizar"),
    path("api/laboratorio/mapeo-web/sesiones/", views.LaboratorioSesionesAPIView.as_view(), name="api_laboratorio_sesiones"),
    path("api/laboratorio/mapeo-web/sesiones/<int:pk>/", views.LaboratorioSesionDetailAPIView.as_view(), name="api_laboratorio_sesion"),
    path(
        "api/laboratorio/mapeo-web/sesiones/<int:pk>/procesar-seleccionados/",
        views.LaboratorioProcesarSeleccionadosAPIView.as_view(),
        name="api_laboratorio_procesar_seleccionados",
    ),
]
