from django.shortcuts import redirect
from django.urls import path

from . import views


app_name = "oportunidades"

urlpatterns = [
    path("", lambda request: redirect("oportunidades:lista"), name="inicio"),
    path("oportunidades/", views.lista_oportunidades, name="lista"),
    path("oportunidades/<int:pk>/", views.detalle_oportunidad, name="detalle"),
    path("oportunidades/<int:pk>/estado/<str:nuevo_estado>/", views.cambiar_estado_oportunidad, name="cambiar_estado"),
    path("oportunidades/<int:pk>/recalcular/", views.recalcular_oportunidad, name="recalcular"),
    path("oportunidades/<int:pk>/generar-contenido/", views.generar_contenido_oportunidad, name="generar_contenido"),
    path("mercadolibre/buscar/", views.buscar_mercado_libre, name="buscar_meli"),
    path("mercadolibre/oauth/iniciar/", views.oauth_iniciar, name="oauth_iniciar"),
    path("mercadolibre/oauth/callback/", views.oauth_callback, name="oauth_callback"),
    path("mercadolibre/oauth/diagnostico/", views.oauth_diagnostico, name="oauth_diagnostico"),
    path("mercadolibre/diagnostico-endpoints/", views.diagnostico_endpoints_meli, name="diagnostico_endpoints_meli"),
    path("fuentes/", views.lista_fuentes, name="lista_fuentes"),
    path("fuentes/<int:pk>/", views.detalle_fuente, name="detalle_fuente"),
    path("decisiones-tecnicas/", views.lista_decisiones_tecnicas, name="lista_decisiones_tecnicas"),
    path("importaciones/", views.lista_importaciones, name="lista_importaciones"),
    path("importaciones/nueva/", views.nueva_importacion, name="nueva_importacion"),
    path("importaciones/plantilla-csv/", views.descargar_plantilla_importacion, name="plantilla_importacion_csv"),
    path("importaciones/<int:pk>/", views.detalle_importacion, name="detalle_importacion"),
    path("importaciones/<int:pk>/procesar/", views.procesar_importacion_view, name="procesar_importacion"),
    path("productos/cargar-url/", views.cargar_producto_url, name="cargar_producto_url"),
    path("productos-multifuente/", views.lista_productos_multifuente, name="lista_productos_multifuente"),
    path("productos-multifuente/<int:pk>/", views.detalle_producto_multifuente, name="detalle_producto_multifuente"),
    path("storage/diagnostico/", views.diagnostico_storage, name="diagnostico_storage"),
    path("conectores/", views.lista_conectores, name="lista_conectores"),
    path("conectores/<int:pk>/", views.detalle_conector, name="detalle_conector"),
    path("conectores/<int:pk>/validar/", views.validar_conector, name="validar_conector"),
    path(
        "productos-multifuente/<int:pk>/recalcular-comparacion/",
        views.recalcular_comparacion_multifuente,
        name="recalcular_comparacion_multifuente",
    ),
    path(
        "productos-multifuente/<int:pk>/recalcular-evaluacion/",
        views.recalcular_evaluacion_multifuente,
        name="recalcular_evaluacion_multifuente",
    ),
    path("api/oportunidades/", views.OportunidadListAPIView.as_view(), name="api_lista"),
    path("api/oportunidades/<int:pk>/", views.OportunidadDetailAPIView.as_view(), name="api_detalle"),
    path("api/oportunidades/<int:pk>/estado/", views.OportunidadEstadoAPIView.as_view(), name="api_estado"),
    path("api/oportunidades/<int:pk>/recalcular/", views.OportunidadRecalcularAPIView.as_view(), name="api_recalcular"),
    path(
        "api/oportunidades/<int:pk>/generar-contenido/",
        views.OportunidadGenerarContenidoAPIView.as_view(),
        name="api_generar_contenido",
    ),
    path("api/meli/buscar/", views.MeliBuscarAPIView.as_view(), name="api_meli_buscar"),
    path("api/meli/sincronizar/", views.MeliSincronizarAPIView.as_view(), name="api_meli_sincronizar"),
    path("api/meli/consultas/", views.MeliConsultasAPIView.as_view(), name="api_meli_consultas"),
    path("api/fuentes/", views.FuenteWebListAPIView.as_view(), name="api_fuentes"),
    path("api/fuentes/<int:pk>/", views.FuenteWebDetailAPIView.as_view(), name="api_fuente_detalle"),
    path("api/decisiones-tecnicas/", views.DecisionTecnicaListAPIView.as_view(), name="api_decisiones_tecnicas"),
    path("api/productos-canonicos/", views.ProductoCanonicoListAPIView.as_view(), name="api_productos_canonicos"),
    path("api/productos-fuente/", views.ProductoFuenteListAPIView.as_view(), name="api_productos_fuente"),
    path("api/importaciones/", views.ImportacionProductosListCreateAPIView.as_view(), name="api_importaciones"),
    path("api/importaciones/<int:pk>/", views.ImportacionProductosDetailAPIView.as_view(), name="api_importacion_detalle"),
    path(
        "api/importaciones/<int:pk>/procesar/",
        views.ImportacionProductosProcesarAPIView.as_view(),
        name="api_importacion_procesar",
    ),
    path("api/productos-multifuente/", views.ProductoMultifuenteListAPIView.as_view(), name="api_productos_multifuente"),
    path(
        "api/productos-multifuente/<int:pk>/",
        views.ProductoMultifuenteDetailAPIView.as_view(),
        name="api_producto_multifuente_detalle",
    ),
    path("api/productos/cargar-url/", views.CargaProductoURLAPIView.as_view(), name="api_cargar_producto_url"),
    path("api/conectores/", views.ConectorFuenteListAPIView.as_view(), name="api_conectores"),
    path("api/conectores/<int:pk>/", views.ConectorFuenteDetailAPIView.as_view(), name="api_conector_detalle"),
    path("api/conectores/<int:pk>/validar/", views.ConectorFuenteValidarAPIView.as_view(), name="api_conector_validar"),
    path("api/ejecuciones-conector/", views.EjecucionConectorListAPIView.as_view(), name="api_ejecuciones_conector"),
    path(
        "api/ejecuciones-conector/<int:pk>/",
        views.EjecucionConectorDetailAPIView.as_view(),
        name="api_ejecucion_conector_detalle",
    ),
]
