services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: radar_sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    volumes:
      - sqlserver_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radar_django
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000 --noreload

volumes:
  sqlserver_data:
